Smb color addition
sproutsocial/seeds-packets pull request #284
Opened 2021-12-10 21:06 UTC by monica-gr

No JIRA story, it is more a dependency of the BCT-3951 story

## Description:

- added colors: teal-100-o-80p, teal-600-o-40p, and neutral-0-o-40p
- added a radius: br--hero_leaf 
Reasoning behind these changes: the colors were to achieve a color in the design and the radius was added incase this design is used more in the future as using the normal leaf radius left it eclipsing in the bottom-right corner where it should have been a full bleed.

## Screenshots:
<img width="1113" alt="Screen Shot 2021-12-10 at 9 50 15 AM" src="https://user-images.githubusercontent.com/91143390/145641101-92f466ad-3692-4cb8-8916-23e7629a37a0.png">
<img width="747" alt="Screen Shot 2021-12-10 at 2 46 26 PM" src="https://user-images.githubusercontent.com/91143390/145641166-d62a7cc6-4c3e-43f5-941e-12272273c41d.png">
<img width="583" alt="Screen Shot 2021-12-10 at 9 48 23 AM" src="https://user-images.githubusercontent.com/91143390/145641167-65a18f9d-009e-4486-98fb-e80f02bdbadc.png">

2021-12-14 22:33 UTC, stanton47 reviewed
Thanks for your patience, @monica-gr!

I looked through this today — the generated `/dist/seedlings-marketing.css` and all of the `/src/` files look great! 🌟 a.k.a. all your changes are 🔥 

I'm not sure if we want to update Lerna version though (`yarn.lock` and `package.json`) → @conwaydev what are your thoughts?

I also think we don't want to include the `package-lock.json` but I need to defer to @conwaydev's expertise on this one too

2021-12-15 18:19 UTC, conwaydev commented
@stanton47 good call out, reset the dependency changes, @monica-gr you may want to go through the rebase steps we talked about yesterday, if you see we have a merge conflict on a couple files. Take a look at https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase or https://learntechsystems.com/git-rebase-and-resolve-conflicts-through-the-github-desktop/

2021-12-17 20:08 UTC, stanton47 approved these changes
Thanks for addressing my questions, @conwaydev!

@monica-gr 🔥 job here, this looks good to me!

2021-12-27 16:30 UTC, jritterbush requested changes
After you rebase....I have a small favor, too 🙏 

Can you add the opacity bg for the pillar CTA section. The new business YIS page will need it and we can also update the pillar templates to use this new one instead of what I hard-coded in the template SCSS.

<img width="1292" alt="Screen Shot 2021-12-27 at 10 29 37" src="https://user-images.githubusercontent.com/474432/147490243-ed463ae5-7e46-40ee-b13e-8c28852aef4b.png">


**Comment:**
```
    --teal-1000-o-40p: Teal 1000 (40% opacity)
```

**Breakpoint SCSS**
```
      .bg--teal-1000-o-40p#{$breakpoint-name} {
        background-color: rgba(get-color(teal, 1000), .4);
      }
```

**Non-breakpoint SCSS** (in else block)
```
    .bg--teal-1000-o-40p {
      background-color: rgba(get-color(teal, 1000), .4);
    }
```

2021-12-27 22:58 UTC, monica-gr commented
Sweet, I've rebased and added teal-1000-o-40p

2021-12-27 23:10 UTC, jritterbush approved these changes
I called out one line that was removed. If it's intentional this looks good to me. Nice work.

2021-12-27 23:10 UTC, jritterbush commented on packets/seedlings/src/_border-radius.scss
> -Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p>
Just making sure this was intentionally removed. Sometimes in rebase if the same line was edited by 2 people it is easy to replace a line with your line when you actually want both.

2021-12-29 15:16 UTC, monica-gr commented on packets/seedlings/src/_border-radius.scss
> -Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p>
That was not intentional! I re-added it back and detailed the hero_leaf class a bit more

2021-12-29 15:27 UTC, jritterbush commented on packets/seedlings/dist/seedlings-marketing.css
> +    Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p>
@monica-gr I'm not sure if indentation has any value in how these comments are parsed but you might want to outdent this example line to align with the other examples in other files.
```suggestion
Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p> 
```

2021-12-29 15:30 UTC, conwaydev approved these changes
Awesome work! When this gets merged go ahead and create a develop -> main PR, that’s going to publish a new version of seedlings that we can update on your web-insights-application PR

2021-12-29 15:37 UTC, jritterbush commented on packets/seedlings/dist/seedlings-marketing.css
> +    Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p>
@conwaydev does the indent do anything here? I called it out but only because I'm not sure how the example or modifier blocks are read by other services

2021-12-29 15:38 UTC, jritterbush approved these changes
Thanks for the updates! Nice work again.

2021-12-29 15:38 UTC, monica-gr commented on packets/seedlings/dist/seedlings-marketing.css
> +    Example: <div class="db square750 bg--neutral-200 overflow-hidden {{modifier}}"></div><p>{{label}}</p>
Thank you!

2021-12-29 15:40 UTC, merged